apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "7777"
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: hello-boot
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/huntedhappy/tanzu-java-web-app
      ref:
        branch: main
